export const colorPrimary = '#1b85b8'
export const colorPrimaryDark = '#156a93'
export const colorAccent = '#fbc02d'
export const colorBase = '#f4f4f4'
export const colorTextDefault = '#191919'

export const colorWhite = '#ffffff'
export const colorIce = '#fcfcfc'
export const colorGreen = '#96ceb4'
export const colorDarkGreen = '#87b9a2'
export const colorRed = '#ff6f69'
export const colorDarkRed = '#e5635e'
export const colorBlack = '#000000'
export const colorGray = '#e8e8e8'

export const colorTransparent = 'transparent'