export const decksTitle = 'Decks'
export const newDeckTitle = 'NewDeck'
export const homeTitle = 'Home'
export const quizTitle = 'Quiz'
export const newQuestionTitle = 'NewQuestion'
export const deckTitle = 'Deck'
export const notificationTitle = 'Flashcards reminds you'
export const whatsTheNameOfYourNewDeckTitle = 'What is the name of your new deck?'